-- Main Initialization file --
require("vishnuarjun.plugins-setup")
require("vishnuarjun.core.options")
require("vishnuarjun.core.keymaps")
require("vishnuarjun.core.colorscheme")
require("vishnuarjun.plugins.comment")
require("vishnuarjun.plugins.nvim-tree")
require("vishnuarjun.plugins.lualine")
require("vishnuarjun.plugins.telescope")
require("vishnuarjun.plugins.nvim-cmp")
-- require("vishnuarjun.plugins.lsp.mason")
-- require("vishnuarjun.plugins.lsp.lspconfig")
-- require("vishnuarjun.plugins.lsp.null-ls")
require("vishnuarjun.plugins.autopairs")
require("vishnuarjun.plugins.treesitter")
require("vishnuarjun.plugins.gitsigns")
require("vishnuarjun.plugins.autoindent")
